name: Publish to Cloudflare
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3 # Favoring picking up security patches versus pinning and avoiding potential supply chain attacks
      # Use the version of npm and Node.js that come with the runner as that wiil always be up-to-date on security patches
      - run: npm ci # Cache node_modules if it gets too slow

      - name: Publish to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler publish