name = "demo-with-custom-backend"
main = "src/index.js"
compatibility_date = "2023-03-18"

[[r2_buckets]]
binding = 'BLOB_STORAGE' # <~ valid JavaScript variable name
bucket_name = 'a11y-analytics-e2e-demo-storage'

[durable_objects]
bindings = [
  { name = "R2Cache", class_name = "R2Cache" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["R2Cache"] # Array of new classes
